### ISSUE TITLE
Running  java -jar fb-inserter.jar >> insert.log never stops.

### ISSUE THREAD

**Issue by pacid** [yhegde/fb-page-scraper#3]
Version:  1.32. 

Running  java -jar fb-inserter.jar >> insert.log never stops and gives no result.

Would be awesome if you could add some instruction on how to compile jars by ourselves. I've got maven compining it - but it gernerates classes.

**Comment by yhegde** [comment]
Did you run the command in the background?
java -jar fb-inserter.jar >> insert.log 2>&1 &
What logs do you see in insert.log?

**Comment by pacid** [comment]
Yes, I have tried running it using various combinations:
java -jar fb-inserter.jar >> insert.log 2>&1 &
java -jar fb-inserter.jar >> insert.log 

The log contains a few lines like that:
"base directory is /tmp/xxx" (where xxx my folder where all the jsons are strored)

**Comment by yhegde** [comment]
I suggest you set your base directory to something other than /tmp/ directory in your config.properties file. eg.
baseDir=/home/yatish/facebook
Did you check if your base directory contains 'download' directory that has json files?
I should have collected json files in the baseDir/download folder before running fb-inserter.jar. 
And your baseDir should be same for both fb-data-collector.jar and fb-inserter.jar.
Hope that is clear now.
